---
title: "Prophage data visualization"
author: "Lakhansing Pardeshi"
date: "`r Sys.Date()`"
output:
  html_document:
    code_download: true
    code_folding: show
    toc: true
    toc_float: true
---

<!-- ```{css, echo=FALSE} -->
<!-- .scroll-100 { -->
<!--   overflow-x: auto; -->
<!--   overflow-y: auto; -->
<!--   background-color: inherit; -->
<!-- } -->
<!-- ``` -->

```{r, setup, include=FALSE}
suppressPackageStartupMessages(library(here))
knitr::opts_knit$set(root.dir = here::here())
```

## Initial setup

```{r}
#!/usr/bin/env Rscript

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(org.Pectobacterium.spp.pan.eg.db))
suppressPackageStartupMessages(library(skimr))
suppressPackageStartupMessages(library(visNetwork))
suppressPackageStartupMessages(library(igraph))
suppressPackageStartupMessages(library(ggraph))
suppressPackageStartupMessages(library(ggnewscale))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(circlize))

# visualize the prophage network
rm(list = ls())

source("https://raw.githubusercontent.com/lakhanp1/omics_utils/main/RScripts/utils.R")
source("scripts/utils/config_functions.R")
source("scripts/utils/homology_groups.R")
source("scripts/utils/genome_scale_utils.R")
################################################################################
set.seed(124)

confs <- prefix_config_paths(
  conf = suppressWarnings(configr::read.config(file = "project_config.yaml")),
  dir = "."
)

pangenome <- confs$data$pangenomes$pectobacterium.v2$name
panConf <- confs$data$pangenomes[[pangenome]]

outDir <- confs$analysis$prophages$dir
outPrefix <- ""

orgDb <- org.Pectobacterium.spp.pan.eg.db

################################################################################
```


## Import data

```{r}
sampleInfo <- get_metadata(file = panConf$files$metadata, genus = confs$genus)

sampleInfoList <- as.list_metadata(
  df = sampleInfo, sampleId, sampleName, SpeciesName, strain, nodeLabs, Genome
)

# read prophage HGs stored locally
proHgs <- suppressMessages(
  readr::read_tsv(confs$analysis$prophages$files$prophage_hg)
) %>% 
  dplyr::mutate(
    hgs = stringr::str_split(hgs, ";")
  ) %>% 
  dplyr::left_join(
    y = dplyr::select(sampleInfo, sampleId, SpeciesName, Genome, N50), by = "sampleId"
  ) 

prophageDf <- suppressMessages(readr::read_tsv(confs$data$prophages$files$data)) %>% 
  dplyr::select(prophage_id, prophage_length = length, completeness)

```

## DAG exploration

Generate an igraph data structure for prophage relationships

```{r}
# import prophage relationships as igraph
gf <- prophage_igraph(file = confs$analysis$prophages$files$network,
                      nodeAn = prophageDf, key = "prophage_id")

gf
```


```{r}
# components of graph
igraph::count_components(gf)
clu <- igraph::components(gf)
compL <- igraph::groups(clu)

```

There should be only two elements when clique detection algorithm is run. One 
for the nodes and second for the links. If there are more than 2 elements, there
is a possibility of cycles in the graph.

```{r}
clique_size_counts(gf)
# largest_cliques(gf)
```

### visualize DAG

```{r}
# DAG visualization 
gf %>% 
  plot(vertex.size = 1.5, vertex.label = NA,
       edge.arrow.size = 0.3, edge.color = "black")

gf %>% 
  add_layout_(igraph::as_tree(), component_wise()) %>% 
  plot(vertex.size = 1.5, vertex.label = NA,
       edge.arrow.size = 0.3, edge.color = "black")

gf %>% 
  igraph::add_layout_(igraph::with_kk(), igraph::component_wise()) %>%
  plot(vertex.size = 1.5, vertex.label = NA,
       edge.arrow.size = 0.3, edge.color = "black")

# visualization
# layout
lot <- layout_with_mds(graph = gf, dim = 2)
lot <- layout_with_dh(graph = gf)
lot <- layout_with_sugiyama(graph = gf)
lot <- layout_with_lgl(graph = gf)
lot <- layout_with_kk(graph = gf)
lot <- layout_with_fr(graph = gf)

plot(gf, layout = lot, vertex.size = 1.5, vertex.label = NA,
     edge.arrow.size = 0.3, edge.color = "black")


```

### Plot graph using `ggraph`

```{r}
# each component layout first and then arranged
lotc <- igraph::layout_components(graph = gf, layout = layout_with_kk)
# plot(gf, layout = lotc, vertex.size = 1.5, vertex.label = NA,
#      edge.arrow.size = 0.3, edge.color = "black")

(pt_net <- ggraph::ggraph(gf, layout = lotc) +
    ggraph::geom_edge_link(
      # mapping = aes(color = weight),
      arrow = arrow(length = unit(1, 'mm')),
      end_cap = circle(1, 'mm')
    ) +
    # scale_colour_viridis_c(option = "A") +
    # ggnewscale::new_scale_colour() +
    # geom_node_point(mapping = aes(color = nodeType, size = nodeType), alpha = 0.7) +
    ggraph::geom_node_point(
      mapping = aes(color = nodeType, size = nodeType),
      alpha = 0.7
    ) +
    scale_color_manual(
      values = c("child" = "black", "root" = "#d95f02", "singleton" = "#7570b3")
    ) +
    scale_size_manual(
      values = c("child" = 1.5, "root" = 3, "singleton" = 1.5)
    ) +
    labs(title = "pangenome prophage hierarchy") +
    theme_void(base_size = 18) +
    theme(
      legend.position = "bottom"
    ))

ggsave(filename = paste(outDir, "/prophage_clusters.pdf", sep = ""),
       width = 12, height = 10)

```
