author: "Lakhansing Pardeshi"
project:
  title: "Pectobacterium pangenome data analysis"
  type: website
  output-dir: "./docs"
  execute-dir: project
  render:
    - scripts/notebooks/index.qmd
    - scripts/notebooks/preprocessing.md
    - scripts/notebooks/pangenome_construction.md
    - scripts/notebooks/pangenome_analysis.md
    - scripts/analysis/HG_summary.qmd
    - scripts/analysis/pangenome_metadata.viz.qmd
    - scripts/analysis/ani.clustering.qmd
    - scripts/analysis/phylo.viz_tree.qmd
    - scripts/analysis/prophage_summary.qmd
    - scripts/analysis/prophage_seq_similarity.qmd
    - scripts/analysis/prophage_clustering.qmd
    - scripts/analysis/prophage_cluster_summary.qmd
    - scripts/notebooks/prophage_analysis.md
    - scripts/ms_figures/supplementary_tables.qmd
execute:
  freeze: true # never re-render during project render
website:
  title: "Pectobacterium pangenome data analysis"
  repo-url: https://github.com/lakhanp1/Pectobacterium_pangenome
  repo-actions: [issue]
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lakhanp1/Pectobacterium_pangenome
          - text: Report a bug
            href: https://github.com/lakhanp1/Pectobacterium_pangenome/issues/new
      - icon: twitter
        href: https://x.com/lakhanp01
    contents:
      - scripts/notebooks/index.qmd
      - section: "Preprocessing"
        contents:
          - text: "Preprocessing"
            href: scripts/notebooks/preprocessing.md
          # - text: "Raw data QC"
            # href: 
          - text: "ANI"
            href: scripts/analysis/ani.clustering.qmd
      - section: "Pangenome"
        contents:
          - text: "Pangenome metadata"
            href: scripts/analysis/pangenome_metadata.viz.qmd        
          - text: "Build"
            href: scripts/notebooks/pangenome_construction.md
          - text: "Analysis"
            href: scripts/notebooks/pangenome_analysis.md
          - text: "Pangenome summary"
            href: scripts/analysis/HG_summary.qmd
          - text: "Phylogeny"
            href: scripts/analysis/phylo.viz_tree.qmd
      - section: "Prophages"
        contents:
          - text: "Analysis"
            href: scripts/notebooks/prophage_analysis.md
          - text: "Prophage summary"
            href: scripts/analysis/prophage_summary.qmd
          - text: "Clustering"
            href: scripts/analysis/prophage_clustering.qmd
          - text: "Clustering summary"
            href: scripts/analysis/prophage_cluster_summary.qmd
      - text: "Supplementary tables"
        href: scripts/ms_figures/supplementary_tables.qmd
format:
  html: 
    toc: true
    toc-depth: 3
    html-math-method: katex
    code-fold: show
    code-tools: true
    code-overflow: scroll
    code-copy: true
    code-line-numbers: true
    css: ./scripts/utils/quarto_style.css
