author: "Lakhansing Pardeshi"
project:
  title: "Pectobacterium pangenome data analysis"
  # output-dir: "./scripts/quarto"
  execute-dir: project
format:
  html: 
    toc: true
    toc-depth: 3
    html-math-method: katex
    code-fold: show
    code-tools: true
    code-overflow: scroll
    code-copy: true
    code-line-numbers: true
    css: ./scripts/utils/quarto_style.css
