---
title: "Pectobacterium pangenome"
genus: "Pectobacterium"
parameters:
  cutoff_busco: 99
  seed: 124
colors:
  core: "#009E73"
  accessory: "#0072B2"
  unique: "#D55E00"
  presence: ""
  absence: "black"
treeDims:
  width: 14
  height: 20
  scale: 2
data:
  dir: "data"
  include_source: ["NCBI", "NAK", "NVWA"]
  reference_data:
    dir: "reference_data"
    files:
      inhouse_metadata: "inhouse_samples_metadata.txt"
      assembly_xml: "assembly_docsum.xml"
      biosample_xml: "biosample_docsum.xml"
      local_ass_ids: "local_assembly_ids.txt"
      ncbi_ass_ids: "ncbi_assembly_ids.txt"
      assembly_ids: "assembly_ids.txt"
      local_metadata: "inhouse_samples_metadata.txt"
      metadata: "sample_metadata.tsv"
      metadata_xls: "sample_metadata.xlsx"
      taxo_correction: "taxonomy_manual_correction.tab"
  analysis_confs:
    dir: "analysis_configs"
    files:
      temp: "temp.txt"
  other:
    dir: "other"
    files:
      ani_report: "ANI_report_prokaryotes.txt"
      assay_probes: "pecto_assay/pectobacterium_assay_probes.fasta"
      probe_info: "pecto_assay/probe_info.txt"
      pecto1_metadata: "pecto1_data/WUR_assemblies_metadata.txt"
  prokka:
    dir: "prokka_annotation"
  interproscan:
    dir: "interproscan"
  cog:
    dir: "eggnog"
  prophages:
    dir: "prophage_genomad"
    files:
      data: "prophage_summary.tab"
      ani: "prophage_ANI"
      mash: "mash/prophage_distance.tab"
  plasmids:
    dir: "prophage_genomad"
    files:
      data: "plasmid_summary.tab"
      ani: "plasmid_ANI"
      mash: "mash/plasmid_distance.tab"
  busco_db:
    dir: "busco_downloads"
    lineage: "enterobacterales_odb10"
  busco_genome:
    dir: "busco.geno"
  busco_protein:
    dir: "busco.prot"
  quast:
    dir: "quast"
  pangenomes:
    dir: "pangenomes"
    pectobacterium.ts:
      name: "pectobacterium.ts"
      dir: "pectobacterium.ts"
      db:
        dir: "pectobacterium.ts.DB"
      files:
        input_lock: "input_genomes.tab"
        genomes: "genomes_fa.list"
        gff: "genomes_gff3.list"
        annotations: "functional_annotations.txt"
        metadata: "genomes_metadata.csv"
    pectobacterium.v2:
      dir: "pectobacterium.v2"
      name: "pectobacterium.v2"
      include_source: ["NCBI", "NAK", "NVWA"]
      homology_group_setting: 4
      files:
        input_lock: "input_genomes.tab"
        genomes: "genomes_fa.list"
        gff: "genomes_gff3.list"
        annotations: "functional_annotations.txt"
        cog: "eggnog_annotations.txt"
        metadata: "genomes_metadata.csv"
        combined_fa: "blastdb/genomes_combined.fa"
        go_data: "extracted_data/pangenome_GO.tab"
        chr_info: "extracted_data/pangenome_chr.tab"
        gene_info: "extracted_data/pangenome_gene_info.tab"
        blastdb: "blastdb/genomes_combined.fa"
        genome_chrs: "blastdb/genome_chr_map.tab"
      analysis_confs:
        dir: "analysis_configs"
        files:
          clade_association: "clade_association_config.tab"
          clade_phenotypes: "clade_association_phenotypes.csv"
          species_genomes: "species_wise_genomes.tab"
      db:
        dir: "pectobacterium.v2.DB"
        metrics:
          dir: "metrics"
          files:
            per_genome: "metrics_per_genome.csv"
            per_seq: "metrics_per_sequence.csv"
            metrics: "metrics.txt"
        gene_classification:
          GC.100.0:
            dir: "gene_classification.100.0"
            files:
              tree: "gene_distance.tree"
              groups: "classified_groups.csv"
              core: "core_groups.csv"
              accessory: "accessory_groups.csv"
              unique: "unique_groups.csv"
          GC.95.5:
            dir: "gene_classification.95.5"
            files:
              tree: "gene_distance.tree"
          phenotypes:
            dir: "gene_classification.pheno"
            assay_FN:
              dir: "assay_FN"
              files:
                overview: "gene_classification_phenotype_overview.txt"
                association: "phenotype_association.csv"
            virulent_Pbrasiliense:
              dir: "virulent_Pbrasiliense"
              files:
                overview: "gene_classification_phenotype_overview.txt"
                association: "phenotype_association.csv"
            Pbrasiliense_clade:
              dir: "Pbrasiliense_clade"
              files:
                overview: "gene_classification_phenotype_overview.txt"
                association: "phenotype_association.csv"
        kmer_classification:
          KC.100.0:
            dir: "kmer_classification.100.0"
            files:
              tree: "genome_kmer_distance.tree"
              mash_upgma: "kmer.upgma.newick"
              mash_nj: "kmer.nj.newick"
              mash_dist: "distances_for_tree/genome_mash_distance.csv"
              distinct_kmer_dist: "distances_for_tree/genome_distance_distinct_kmers.csv"
              all_kmer_dist: "distances_for_tree/genome_distance_all_kmers.csv"
          KC.95.5:
            dir: "kmer_classification.95.5"
            files:
              tree: "genome_kmer_distance.tree"
        core_phylogeny:
          default:
            dir: "core_snp_tree"
            files:
              tree_ml: "informative.fasta.treefile"
              tree_nj: ""
          hg_set1:
            dir: "core_snp_tree.hg_set1"
            files:
              tree_ml: ""
              tree_nj: ""
        mlsa:
          mlsa_default:
            dir: "mlsa"
            files:
              fasta: "output/mlsa.fasta"
              alignment: "output/mlsa.afa"
              tree: "output/mlsa.fasta.treefile"
          mlsa_set1:
            dir: "mlsa_set1"
            files:
              fasta: "output/mlsa.fasta"
              alignment: "output/mlsa.afa"
              tree: "output/mlsa.fasta.treefile"
analysis:
  dir: "analysis"
  qc:
    dir: "QC"
    files:
      busco_genome: "busco_geno_multiqc_data/multiqc_busco.txt"
      busco_protein: "busco_prot_multiqc_data/multiqc_busco.txt"
      quast: "quast_multiqc_data/multiqc_quast.txt"
      genome_chr_size: "assembly_chr_size.txt"
      duplicate_genomes: "duplicate_genomes.tab"
      exclude_genomes: "exclude_genomes.txt"
      prebuild_metadata: "prebuild_metadata.tsv"
      prebuild_metadata_xls: "prebuild_metadata.xlsx"
      tax_check: "taxonomy_check.tab"
  ANI:
    ## move this inside "qc" block in future
    dir: "fastANI"
    files:
      fastani_out: "ANI_results"
      ani_upgma: "ANI_UPGMA.newick"
      ani_nj: "ANI_NJ.newick"
      ani_rooted_nj: "ANI_NJ_rooted.newick"
  summary:
    dir: "pangenome_v2/summary"
    files:
      data: ""
      pangenome: ""
  grouping_optimization:
    name: "grouping"
    dir: "pangenome_v2/subset_optimal_group"
  phylogeny:
    name: "phylogeny"
    outgroup: "104326-106-074"
    dir: "pangenome_v2/phylogeny"
    default: "kmer_nj"
    files:
      clade_compare: "clade_compare_contrasts.tab"
    ani:
      dir: "ani"
      files:
        ani_distance: "ANI_distance.pangenome.tab"
        ani_matrix: "ANI_matrix.pangenome.tab"
    # cannot move ani_upgma and ani_nj blocks under ani because tree plotting
    # script depends on phylogeny/[ani_upgma, ani_nj, gene_nj, kmer_nj] structure
    ani_upgma:
      name: "ANI UPGMA"
      dir: "ani"
      files:
        tree: "ANI_UPGMA.pangenome.newick"
        tree_rooted: "ANI_UPGMA.pangenome.rooted.newick"
        species_order: "ANI_UPGMA.species_order.txt"
    ani_nj:
      name: "ANI NJ"
      dir: "ani"
      files:
        tree: "ANI_NJ.pangenome.newick"
        tree_rooted: "ANI_NJ.pangenome.rooted.newick"
        species_order: "ANI_NJ.species_order.txt"
    gene_nj:
      name: "gene distance NJ"
      dir: "gene_dist"
      files:
        tree: "gene_dist.newick"
        tree_rooted: "gene_dist.rooted.newick"
        species_order: "gene_dist.species_order.txt"
    kmer_nj:
      name: "kmer distance NJ"
      dir: kmer_dist
      files:
        tree: "kmer.nj.newick"
        tree_rooted: "kmer.nj.rooted.newick"
        species_order: "kmer.nj.species_order.txt"
    kmer_upgma:
      name: "kmer distance UPGMA"
      dir: kmer_dist
      files:
        tree: "kmer.upgma.newick"
        tree_rooted: "kmer.upgma.rooted.newick"
        species_order: "kmer.upgma.species_order.txt"
    core_snp_ml:
      dir: "core_snp"
      name: "core genome SNP ML"
      files:
        tree: "core_snp_ml.newick"
        tree_rooted: "core_snp_ml.rooted.newick"
        species_order: "core_snp_ml.species_order.txt"
    core_snp_nj:
      dir: "core_snp"
      name: "core genome SNP NJ"
      files:
        tree: "core_snp_nj.newick"
        tree_rooted: "core_snp_nj.rooted.newick"
        species_order: "core_snp_nj.species_order.txt"
  insilico_assay:
    dir: "pangenome_v2/insilico_assay"
    files:
      blastn: "pcr_primer_blastn.out"
      insilico_pcr: "bioassay_probe_match.data.tab"
  homology_groups:
    dir: "pangenome_v2/homology_groups"
    files:
      groups: "genome_to_groups.tab"
      groups_meta: "homology_groups_meta.tab"
      spp_group_go: "spp_group_GO.tab"
      spp_group_stats: "spp_group_stats.tab"
      hg_sets: "hg_sets_of_interest.tab"
  association:
    dir: "pangenome_v2/pheno_association"
    files:
      pheno_specific_groups: "phenotype_specific_groups.txt"
  prophages:
    cutoff_length: 5000
    dir: "pangenome_v2/prophages"
    preprocessing:
      dir: "preprocessing"
      files:
        raw_prophage_hg: "prophage_hgs.tab"
        consolidated: "consolidated_phages.tab"
        filtered: "filtered_prophages.tab"
        pair_comparison: "phage_pair_relationships.tab"
        hgs_union: "prophage_hgs_union.tab"
        dag_clusters: "prophage_DAG_network.tab"
        ap_clusters: "ap_clusters.tab"
        apc_summary: "ap_cluster_summary.tab"
        apc_exemplar_phylo: "ap_cluster_exemplar.newick"
        ani_dist: "prophage_ani_dist.tab"
        ani_hclust: "prophage_ani_hclust.newick"
        ani_nj: "prophage_ani_nj.newick"
        mash_dist: "prophage_mash_dist.tab"
        mash_hclust: "prophage_mash_hclust.newick"
        mash_nj: "prophage_mash_nj.newick"
    files:
      prophage_stats_species: "prophage_stats_species.tab"
      prophage_stats_genome: "prophage_stats_genome.tab"
      clusters: "prophages_clusters.tab"
      prophage_hg_info: "prophage_HG_info.tab"
      hg_broad_functions: "prophage_HG_broad_functions.tab"
  plasmids:
    cutoff_length: 0
    dir: "pangenome_v2/plasmids"
    preprocessing:
      dir: "preprocessing"
      files:
        raw_plasmid_hg: "plasmid_hgs.tab"
        consolidated: "consolidated_plasmids.tab"
        filtered: "filtered_plasmids.tab"
        pair_comparison: "plasmid_pair_relationships.tab"
        hgs_union: "plasmid_hgs_union.tab"
        ani_dist: "plasmid_ani_dist.tab"
        ani_hclust: "plasmid_ani_hclust.newick"
        ani_nj: "plasmid_ani_nj.newick"
        mash_dist: "plasmid_mash_dist.tab"
        mash_hclust: "plasmid_mash_hclust.newick"
        mash_nj: "plasmid_mash_nj.newick"
    files:
      stats_species: "plasmid_stats_species.tab"
      stats_genome: "plasmid_stats_genome.tab"
      clusters: "plasmid_clusters.tab"
