---
title: "Pectobacterium pangenome"
genus: "Pectobacterium"
parameters:
  cutoff_busco: 99
  seed: 124
data:
  dir: "data"
  include_source: ['NCBI', 'NAK', 'NVWA']
  reference_data:
    dir: "reference_data"
    files:
      inhouse_metadata: "inhouse_samples_metadata.txt"
      assembly_xml: "assembly_docsum.xml"
      biosample_xml: "biosample_docsum.xml"
      local_ass_ids: "local_assembly_ids.txt"
      ncbi_ass_ids: "ncbi_assembly_ids.txt"
      assembly_ids: "assembly_ids.txt"
      local_metadata: "inhouse_samples_metadata.txt"
      metadata: "sample_metadata.tsv"
      metadata_xls: "sample_metadata.xlsx"
      taxo_correction: "taxonomy_manual_correction.tab"
  analysis_confs:
    dir: "analysis_configs"
    files:
      phenotype_association: "pheno_association_config.tab"
  other:
    dir: "other"
    files:
        ani_report: "ANI_report_prokaryotes.txt"
        assay_probes: "pecto_assay/pectobacterium_assay_probes.fasta"
        probe_info: "pecto_assay/probe_info.txt"
        pecto1_metadata: "pecto1_data/WUR_assemblies_metadata.txt"
  prokka:
    dir: "prokka_annotation"
  interproscan:
    dir: "interproscan"
  busco_db:
    dir: "busco_downloads"
  busco_genome:
    dir: "busco.geno"
  busco_protein:
    dir: "busco.prot"
  pangenomes:
    dir: "pangenomes"
    pectobacterium.10g:
      name: "pectobacterium.10g"
      dir: "pectobacterium.10g"
      db:
        dir: "pectobacterium.10g.DB"
      files:
        input_lock: "input_genomes.tab"
        genomes: "genomes_fa.list"
        gff: "genomes_gff3.list"
        annotations: "functional_annotations.txt"
        metadata: "genomes_metadata.csv"
    pectobacterium.v2:
      dir: "pectobacterium.v2"
      name: "pectobacterium.v2"
      homology_group_setting: 4
      files:
        input_lock: "input_genomes.tab"
        genomes: "genomes_fa.list"
        gff: "genomes_gff3.list"
        annotations: "functional_annotations.txt"
        metadata: "genomes_metadata.csv"
        combined_fa: "blastdb/genomes_combined.fa"
        blastdb: "blastdb/genomes_combined.fa"
        genome_chrs: "blastdb/genome_chr_map.tab"
      db:
        dir: "pectobacterium.v2.DB"
        gene_classification:
          GC.100.0:
            dir: "gene_classification.100.0"
            files:
              tree: "gene_distance.tree"
              groups: "classified_groups.csv"
              core: "core_groups.csv"
              accessory: "accessory_groups.csv"
              unique: "unique_groups.csv"
          GC.95.5:
            dir: "gene_classification.95.5"
            files:
              tree: "gene_distance.tree"
          phenotypes:
            dir: "gene_classification.pheno"
            assay_FN:
              dir: "assay_FN"
              files:
                overview: "gene_classification_phenotype_overview.txt"
                association: "phenotype_association.csv"
            virulent_Pbrasiliense:
              dir: "virulent_Pbrasiliense"
              files:
                overview: "gene_classification_phenotype_overview.txt"
                association: "phenotype_association.csv"
            Pbrasiliense_clade:
              dir: "Pbrasiliense_clade"
              files:
                overview: "gene_classification_phenotype_overview.txt"
                association: "phenotype_association.csv"
        kmer_classification:
          KC.100.0:
            dir: "kmer_classification.100.0"
            files:
              tree: "genome_kmer_distance.tree"
          KC.95.5:
            dir: "kmer_classification.95.5"
            files:
              tree: "genome_kmer_distance.tree"
        core_phylogeny:
          default:
            dir: "core_snp_tree"
            files:
              tree_ml: "informative.fasta.treefile"
              tree_nj: ""
          hg_set1:
            dir: "core_snp_tree.hg_set1"
            files:
              tree_ml: ""
              tree_nj: ""
        mlsa:
          mlsa_default:
            dir: "mlsa"
            files:
              fasta: "output/mlsa.fasta"
              alignment: "output/mlsa.afa"
              tree: "output/mlsa.fasta.treefile"
          mlsa_set1:
            dir: "mlsa_set1"
            files:
              fasta: "output/mlsa.fasta"
              alignment: "output/mlsa.afa"
              tree: "output/mlsa.fasta.treefile"
analysis:
  dir: "analysis"
  qc:
    dir: "01_QC"
    files:
      busco_genome: "busco_geno_multiqc_data/multiqc_busco.txt"
      busco_protein: "busco_prot_multiqc_data/multiqc_busco.txt"
      quast: "quast_multiqc_data/multiqc_quast.txt"
      genome_chr_size: "assembly_chr_size.txt"
      duplicate_genomes: "duplicate_genomes.tab"
      exclude_genomes: "exclude_genomes.txt"
      prebuild_metadata : "prebuild_metadata.tsv"
      prebuild_metadata_xls: "prebuild_metadata.xlsx"
      tax_check: "taxonomy_check.tab"
  ANI:
    ## move this inside "qc" block in future
    dir: "02_fastANI"
    files:
      fastani_out: "ANI_results"
      ani_upgma: "ANI_UPGMA.newick"
      ani_nj: "ANI_NJ.newick"
      ani_rooted_nj: "ANI_NJ_rooted.newick"
  gouping_optimization:
    name: "grouping"
    dir: "04_pangenome_pecto_v2/subset_optimal_group"
  phylogeny:
    name: "phylogeny"
    outgroup: "104326-106-074"
    dir: "04_pangenome_pecto_v2/phylogeny"
    default: "kmer_nj"
    files:
      clade_copare: "clade_compare_contrasts.tab"
      clade_phenotypes: "clade_compare_phenotypes.csv"
    ani:
      dir: "ani"
      files:
        ani_distance: "ANI_distance.pangenome.tab"
        ani_matrix: "ANI_matrix.pangenome.tab"
    # cannot move ani_upgma and ani_nj blocks under ani because tree plotting
    # script depends on phylogeny/[ani_upgma, ani_nj, gene_nj, kmer_nj] structure
    ani_upgma:
      name: "ANI UPGMA"
      dir: "ani"
      files:
        tree: "ANI_UPGMA.pangenome.newick"
        tree_rooted: "ANI_UPGMA.pangenome.rooted.newick"
        species_order: "ANI_UPGMA.species_order.txt"
    ani_nj:
      name: "ANI NJ"
      dir: "ani"
      files:
        tree: "ANI_NJ.pangenome.newick"
        tree_rooted: "ANI_NJ.pangenome.rooted.newick"
    gene_nj:
      name: "gene distance NJ"
      dir: "gene_dist"
      files:
        tree: "gene_dist.newick"
        tree_rooted: "gene_dist.rooted.newick"
    kmer_nj:
      name: "kmer distance NJ"
      dir: kmer_dist
      files:
        tree: "kmer_dist.newick"
        tree_rooted: "kmer_dist.rooted.newick"
    core_snp_ml:
      dir: "core_snp"
      name: "core genome SNP ML"
      files:
        tree: "core_snp_ml.newick"
        tree_rooted: "core_snp_ml.rooted.newick"
    core_snp_nj:
      dir: "core_snp"
      name: "core genome SNP NJ"
      files:
        tree: "core_snp_nj.newick"
        tree_rooted: "core_snp_nj.rooted.newick"
  insilico_assay:
    dir: "04_pangenome_pecto_v2/insilico_assay"
    files:
      blastn: "probe_blastn.out"
  homology_groups:
    dir: "04_pangenome_pecto_v2/homology_groups"
    files:
      groups: "genome_to_groups.tab"
      groups_meta: "homology_groups_meta.tab"
  association:
    dir: "04_pangenome_pecto_v2/pheno_association"
    files:
      config: "clade_comarison_config.tab"
      phenotypes: "clade_comarison_phenotypes.csv"
      pheno_specific_groups: "phenotype_specific_groups.txt"
...